# Generated by Django 3.0.3 on 2020-06-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='top_name',
            new_name='topic_name',
        ),
    ]
